services:
  app:
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: schoolmanagement-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

volumes:
  db-data:
