services:
  app:
    build: .
    container_name: schoolmanagement-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: schoolmanagement-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: schoolmanagement-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: schoolmanagement-redisinsight
    ports:
      - "${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}"
    depends_on:
      - redis

volumes:
  db-data:
